services:
  mongo_db:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017

  api:
    container_name: api
    build: .
    ports:
      - 8080
    environment:
      MONGO_URI: mongodb://localhost:27017/backend3
